###
POST http://localhost:3000/auth/test HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocGFpazIiLCJpYXQiOjE3MjY2Njc0ODYsImV4cCI6MTcyNjY3MTA4Nn0.4KASVHmzHlWijkh4YShxyfLiV63_mk2TLYYBcSLeZVE

###
POST http://localhost:3000/auth/signin HTTP/1.1
content-type: application/json

{
    "username": "chpaik2",
    "password": "123456"
}

###
POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "chpaik2",
    "password": "123456"
}

###
POST http://localhost:3000/auth/signup HTTP/1.1
content-type: application/json

{
    "username": "qwer",
    "password": "!@#$%!@@##!@"
}

###
POST http://localhost:3000/boards HTTP/1.1
content-type: application/json

{
    "title": "Board 1",
    "description": "Description 1"
}

###
POST http://localhost:3000/boards HTTP/1.1
content-type: application/json

{
    "title": "Board 2",
    "description": "Description 2"
}

###
POST http://localhost:3000/boards HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocGFpazIiLCJpYXQiOjE3MjY2NjkwMjUsImV4cCI6MTcyNjY3MjYyNX0.LnHI9lgvoWjDAiQCAQOr56-RZiFw7CAg9XNgk846RkA

{
    "title": "Board 8 - by chpaik2",
    "description": "Description 8"
}

###
# chpaik1
GET http://localhost:3000/boards
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocGFpazEiLCJpYXQiOjE3MjY2Njg5NTgsImV4cCI6MTcyNjY3MjU1OH0.ca5ZDm2A3DEeefLplXPpijoXWtH5P_fPG4EsBjO1h5Y

###
# chpaik2
GET http://localhost:3000/boards
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocGFpazIiLCJpYXQiOjE3MjY2NjkwMjUsImV4cCI6MTcyNjY3MjYyNX0.LnHI9lgvoWjDAiQCAQOr56-RZiFw7CAg9XNgk846RkA


###
DELETE http://localhost:3000/boards/7
content-type: application/json
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocGFpazEiLCJpYXQiOjE3MjY2Njg5NTgsImV4cCI6MTcyNjY3MjU1OH0.ca5ZDm2A3DEeefLplXPpijoXWtH5P_fPG4EsBjO1h5Y # chpaik1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocGFpazIiLCJpYXQiOjE3MjY2NjkwMjUsImV4cCI6MTcyNjY3MjYyNX0.LnHI9lgvoWjDAiQCAQOr56-RZiFw7CAg9XNgk846RkA # chpaik2

###
GET http://localhost:3000/boards/1

###
GET http://localhost:3000/boards/2

###
DELETE http://localhost:3000/boards/3

###
PATCH  http://localhost:3000/boards/2/status
content-type: application/json

{
  "status": "PRIVATE"
}
