POST http://localhost:3000/boards HTTP/1.1
content-type: application/json

{
    "title": "Board 1",
    "description": "Description 1"
}

###
POST http://localhost:3000/boards HTTP/1.1
content-type: application/json

{
    "title": "Board 2",
    "description": "Description 2"
}

###
GET http://localhost:3000/boards

###
GET http://localhost:3000/boards/1

###
GET http://localhost:3000/boards/2

###
DELETE http://localhost:3000/boards/4

###
PATCH  http://localhost:3000/boards/adfa4b20-7580-11ef-b9e2-b3ab5454307a/status
content-type: application/json

{
  "status": "PRIVATE"
}
